[0m14:41:55.282627 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029E21A184D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029E21A1B740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029E21A1AFC0>]}


============================== 14:41:55.286324 | 56056521-1208-414e-a91b-1528cb952519 ==============================
[0m14:41:55.286324 [info ] [MainThread]: Running with dbt=1.9.1
[0m14:41:55.286324 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:41:55.337194 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/marcell.oliveira/.dbt')}
[0m14:41:55.338194 [info ] [MainThread]: Creating dbt configuration folder at 
[0m14:42:43.644675 [debug] [MainThread]: Starter project path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Lib\site-packages\dbt\include\starter_project
[0m14:42:43.720674 [info ] [MainThread]: 
Your new dbt project "dbt_example" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:42:43.721366 [info ] [MainThread]: Setting up your profile.
[0m14:44:28.938840 [info ] [MainThread]: Profile dbt_example written to C:\Users\marcell.oliveira\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:44:28.938840 [debug] [MainThread]: Command `dbt init` succeeded at 14:44:28.938840 after 153.80 seconds
[0m14:44:28.938840 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029E3AB53F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029E38EA2FF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029E1EE411C0>]}
[0m14:44:28.938840 [debug] [MainThread]: Flushing usage events
[0m14:44:29.754899 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m07:49:21.728702 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FDAE17380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FDAE15C70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FDAE162A0>]}


============================== 07:49:21.761070 | 9674c02b-1b31-4b59-b3df-e25f74210f54 ==============================
[0m07:49:21.761070 [info ] [MainThread]: Running with dbt=1.9.1
[0m07:49:21.763068 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m07:49:21.866899 [info ] [MainThread]: dbt version: 1.9.1
[0m07:49:21.867899 [info ] [MainThread]: python version: 3.12.8
[0m07:49:21.868900 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m07:49:21.869408 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m07:49:28.191090 [info ] [MainThread]: Using profiles dir at C:\Users\marcell.oliveira\.dbt
[0m07:49:28.192088 [info ] [MainThread]: Using profiles.yml file at C:\Users\marcell.oliveira\.dbt\profiles.yml
[0m07:49:28.192088 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\marcell.oliveira\Desktop\dbt_example\dbt_project.yml
[0m07:49:28.193088 [info ] [MainThread]: adapter type: bigquery
[0m07:49:28.193088 [info ] [MainThread]: adapter version: 1.9.0
[0m07:49:28.193088 [info ] [MainThread]: Configuration:
[0m07:49:28.194594 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m07:49:28.194594 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m07:49:28.195599 [info ] [MainThread]: Required dependencies:
[0m07:49:28.196599 [debug] [MainThread]: Executing "git --help"
[0m07:49:28.335695 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m07:49:28.335695 [debug] [MainThread]: STDERR: "b''"
[0m07:49:28.335695 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m07:49:28.336743 [info ] [MainThread]: Connection:
[0m07:49:28.339695 [info ] [MainThread]:   method: oauth
[0m07:49:28.340695 [info ] [MainThread]:   database: 1
[0m07:49:28.340695 [info ] [MainThread]:   execution_project: 1
[0m07:49:28.342202 [info ] [MainThread]:   schema: 1
[0m07:49:28.342202 [info ] [MainThread]:   location: US
[0m07:49:28.342202 [info ] [MainThread]:   priority: interactive
[0m07:49:28.343210 [info ] [MainThread]:   maximum_bytes_billed: None
[0m07:49:28.343210 [info ] [MainThread]:   impersonate_service_account: None
[0m07:49:28.343210 [info ] [MainThread]:   job_retry_deadline_seconds: None
[0m07:49:28.344715 [info ] [MainThread]:   job_retries: 1
[0m07:49:28.344715 [info ] [MainThread]:   job_creation_timeout_seconds: None
[0m07:49:28.345720 [info ] [MainThread]:   job_execution_timeout_seconds: 1
[0m07:49:28.345720 [info ] [MainThread]:   timeout_seconds: 1
[0m07:49:28.346726 [info ] [MainThread]:   client_id: None
[0m07:49:28.346726 [info ] [MainThread]:   token_uri: None
[0m07:49:28.347726 [info ] [MainThread]:   dataproc_region: None
[0m07:49:28.348727 [info ] [MainThread]:   dataproc_cluster_name: None
[0m07:49:28.348727 [info ] [MainThread]:   gcs_bucket: None
[0m07:49:28.348727 [info ] [MainThread]:   dataproc_batch: None
[0m07:49:28.349726 [info ] [MainThread]: Registered adapter: bigquery=1.9.0
[0m07:49:29.065770 [debug] [MainThread]: Acquiring new bigquery connection 'debug'
[0m07:49:29.066787 [debug] [MainThread]: On debug: select 1 as id
[0m07:49:29.066787 [debug] [MainThread]: Opening a new connection, currently in state init
[0m07:49:34.025305 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m07:49:34.026312 [info ] [MainThread]: [31m2 checks failed:[0m
[0m07:49:34.027713 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\marcell.oliveira\Desktop\dbt_example\dbt_project.yml> not found

[0m07:49:34.028668 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Runtime Error
  Unable to generate access token, if you're using impersonate_service_account, make sure your initial account has the "roles/iam.serviceAccountTokenCreator" role on the account you are trying to impersonate.
  
  Reauthentication is needed. Please run `gcloud auth application-default login` to reauthenticate.

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m07:49:34.031580 [debug] [MainThread]: Command `dbt debug` failed at 07:49:34.031580 after 12.46 seconds
[0m07:49:34.031580 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m07:49:34.031580 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FDA4BE9F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FF3B67FE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FF22065D0>]}
[0m07:49:34.031580 [debug] [MainThread]: Flushing usage events
[0m07:49:34.662321 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:39:36.965327 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014A252EA060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014A24FD6AE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014A252EA150>]}


============================== 08:39:37.003670 | f37733e3-6517-48ec-b1a6-461e2120e705 ==============================
[0m08:39:37.003670 [info ] [MainThread]: Running with dbt=1.9.1
[0m08:39:37.004623 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m08:39:37.091685 [info ] [MainThread]: dbt version: 1.9.1
[0m08:39:37.092634 [info ] [MainThread]: python version: 3.12.8
[0m08:39:37.093576 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m08:39:37.093576 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m08:39:37.094655 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |   target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m08:39:37.096605 [debug] [MainThread]: Command `dbt debug` failed at 08:39:37.096605 after 0.23 seconds
[0m08:39:37.096605 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014A24CB3980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014A24193B00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014A25318F80>]}
[0m08:39:37.096605 [debug] [MainThread]: Flushing usage events
[0m08:39:37.864981 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:02:46.461332 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D8FBEA150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D8FBEA300>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D8FBEA3C0>]}


============================== 17:02:46.493425 | 3e408f31-c101-4bb9-b2ec-861d062b6ae8 ==============================
[0m17:02:46.493425 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:02:46.493425 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:02:46.584748 [info ] [MainThread]: dbt version: 1.9.1
[0m17:02:46.585770 [info ] [MainThread]: python version: 3.12.8
[0m17:02:46.585770 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:02:46.586750 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:02:46.586750 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m17:02:46.588773 [debug] [MainThread]: Command `dbt debug` failed at 17:02:46.588773 after 0.23 seconds
[0m17:02:46.588773 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D8FC19040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D8F60AEA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D8FBEA3F0>]}
[0m17:02:46.588773 [debug] [MainThread]: Flushing usage events
[0m17:02:47.242650 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:07:40.415479 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B81A0EA180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B819C5EAE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B81A0E9F10>]}


============================== 17:07:40.423157 | 732993b6-185c-4e7e-bd52-72f51f1cc42d ==============================
[0m17:07:40.423157 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:07:40.423542 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:07:40.440832 [info ] [MainThread]: dbt version: 1.9.1
[0m17:07:40.441295 [info ] [MainThread]: python version: 3.12.8
[0m17:07:40.442308 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:07:40.442308 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:07:40.443309 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m17:07:40.444918 [debug] [MainThread]: Command `dbt debug` failed at 17:07:40.444918 after 0.12 seconds
[0m17:07:40.444918 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B819DABEC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B81A118DA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B81A0EA360>]}
[0m17:07:40.444918 [debug] [MainThread]: Flushing usage events
[0m17:07:41.096377 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:09:20.539008 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E7C11EA150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E7C054EAE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E7C11EA0F0>]}


============================== 17:09:20.546055 | 533daefa-650b-4c5c-846d-0c3b23c8d5c1 ==============================
[0m17:09:20.546055 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:09:20.546055 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:09:20.551903 [info ] [MainThread]: dbt version: 1.9.1
[0m17:09:20.551903 [info ] [MainThread]: python version: 3.12.8
[0m17:09:20.551903 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:09:20.564342 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:09:20.564551 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m17:09:20.566558 [debug] [MainThread]: Command `dbt debug` failed at 17:09:20.566558 after 0.13 seconds
[0m17:09:20.566558 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E7C0803620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E7C110D550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E7C1218EC0>]}
[0m17:09:20.567707 [debug] [MainThread]: Flushing usage events
[0m17:09:21.231740 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:10:06.349268 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001735C1EA2A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001735B5BEAE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001735C1EA090>]}


============================== 17:10:06.356274 | a27a0f03-a17e-476f-bbf8-56ee5b3d75ed ==============================
[0m17:10:06.356274 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:10:06.357570 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:10:06.363926 [info ] [MainThread]: dbt version: 1.9.1
[0m17:10:06.363926 [info ] [MainThread]: python version: 3.12.8
[0m17:10:06.363926 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:10:06.363926 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:10:06.363926 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m17:10:06.374436 [debug] [MainThread]: Command `dbt debug` failed at 17:10:06.374436 after 0.12 seconds
[0m17:10:06.374436 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001735C10D580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001735C0D4770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001735C1EA420>]}
[0m17:10:06.374436 [debug] [MainThread]: Flushing usage events
[0m17:10:06.999091 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:19:41.362038 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E30D2EA3C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E30C806AE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E30D2EA300>]}


============================== 17:19:41.368584 | bec9f629-9909-4493-b21c-9220a03467b8 ==============================
[0m17:19:41.368584 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:19:41.370639 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m17:19:41.385481 [info ] [MainThread]: dbt version: 1.9.1
[0m17:19:41.386171 [info ] [MainThread]: python version: 3.12.8
[0m17:19:41.386171 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:19:41.386171 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:19:41.387223 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m17:19:41.389219 [debug] [MainThread]: Command `dbt debug` failed at 17:19:41.388241 after 0.13 seconds
[0m17:19:41.389219 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E30CCB39B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E30D319280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E30D318EC0>]}
[0m17:19:41.389219 [debug] [MainThread]: Flushing usage events
[0m17:19:42.052204 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:23:59.879359 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D96E3EA2D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D96DFE3860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D96E3EA300>]}


============================== 17:23:59.879359 | aa122579-f328-4632-adcd-eb0eb150b183 ==============================
[0m17:23:59.879359 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:23:59.879359 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:23:59.907416 [info ] [MainThread]: dbt version: 1.9.1
[0m17:23:59.908415 [info ] [MainThread]: python version: 3.12.8
[0m17:23:59.908415 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:23:59.909340 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:23:59.910345 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m17:23:59.913345 [debug] [MainThread]: Command `dbt debug` failed at 17:23:59.912346 after 0.12 seconds
[0m17:23:59.913345 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D96E30D2B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D96E43D940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D96E2A1AC0>]}
[0m17:23:59.914346 [debug] [MainThread]: Flushing usage events
[0m17:24:00.556446 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:26:25.467339 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AA9DAEA3C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AA9D57B860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AA9DAEA210>]}


============================== 17:26:25.474864 | 35c021d1-2866-45f4-9d0f-da9452e8931d ==============================
[0m17:26:25.474864 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:26:25.475871 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:26:25.483997 [info ] [MainThread]: dbt version: 1.9.1
[0m17:26:25.483997 [info ] [MainThread]: python version: 3.12.8
[0m17:26:25.483997 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:26:25.483997 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:26:25.483997 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m17:26:25.483997 [debug] [MainThread]: Command `dbt debug` failed at 17:26:25.483997 after 0.11 seconds
[0m17:26:25.483997 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AA9D6A0560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AA9DB19070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AA9DB682C0>]}
[0m17:26:25.483997 [debug] [MainThread]: Flushing usage events
[0m17:26:26.279171 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:27:46.808836 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021A7360A9C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021A7360AA50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021A7360BA70>]}


============================== 17:27:46.808836 | 43e1438f-f753-4de4-8987-940a4eda40ff ==============================
[0m17:27:46.808836 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:27:46.808836 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\Desktop\\dbt_example', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:27:46.831075 [info ] [MainThread]: dbt version: 1.9.1
[0m17:27:46.831075 [info ] [MainThread]: python version: 3.12.8
[0m17:27:46.831075 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:27:46.836337 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:27:46.836337 [info ] [MainThread]: Using profiles dir at C:\Users\marcell.oliveira\Desktop\dbt_example
[0m17:27:46.836337 [info ] [MainThread]: Using profiles.yml file at C:\Users\marcell.oliveira\Desktop\dbt_example\profiles.yml
[0m17:27:46.837392 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\marcell.oliveira\Desktop\dbt_example\dbt_project.yml
[0m17:27:46.838382 [info ] [MainThread]: Configuration:
[0m17:27:46.838382 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m17:27:46.838382 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m17:27:46.839379 [info ] [MainThread]: Required dependencies:
[0m17:27:46.839379 [debug] [MainThread]: Executing "git --help"
[0m17:27:46.904662 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m17:27:46.905663 [debug] [MainThread]: STDERR: "b''"
[0m17:27:46.905663 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m17:27:46.906656 [info ] [MainThread]: Connection test skipped since no profile was found
[0m17:27:46.907657 [info ] [MainThread]: [31m2 checks failed:[0m
[0m17:27:46.908707 [info ] [MainThread]: dbt looked for a profiles.yml file in C:\Users\marcell.oliveira\Desktop\dbt_example\profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m17:27:46.909661 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\marcell.oliveira\Desktop\dbt_example\dbt_project.yml> not found

[0m17:27:46.910730 [debug] [MainThread]: Command `dbt debug` failed at 17:27:46.910730 after 0.26 seconds
[0m17:27:46.911719 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021A73E6A330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021A743B5250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021A73F2BF80>]}
[0m17:27:46.911719 [debug] [MainThread]: Flushing usage events
[0m17:27:47.536522 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:28:49.998038 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002704CA4EB10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002704C206AB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002704C24CB00>]}


============================== 17:28:50.003297 | accf1516-701a-4f69-b3c3-6f474801835b ==============================
[0m17:28:50.003297 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:28:50.003297 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\Desktop\\dbt_example', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'debug', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt debug --log-format debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:28:50.003297 [info ] [MainThread]: dbt version: 1.9.1
[0m17:28:50.018303 [info ] [MainThread]: python version: 3.12.8
[0m17:28:50.018303 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:28:50.018303 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:28:50.019778 [info ] [MainThread]: Using profiles dir at C:\Users\marcell.oliveira\Desktop\dbt_example
[0m17:28:50.020515 [info ] [MainThread]: Using profiles.yml file at C:\Users\marcell.oliveira\Desktop\dbt_example\profiles.yml
[0m17:28:50.020634 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\marcell.oliveira\Desktop\dbt_example\dbt_project.yml
[0m17:28:50.021944 [info ] [MainThread]: Configuration:
[0m17:28:50.022591 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m17:28:50.023018 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m17:28:50.023307 [info ] [MainThread]: Required dependencies:
[0m17:28:50.023736 [debug] [MainThread]: Executing "git --help"
[0m17:28:50.089008 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m17:28:50.089603 [debug] [MainThread]: STDERR: "b''"
[0m17:28:50.089603 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m17:28:50.089603 [info ] [MainThread]: Connection test skipped since no profile was found
[0m17:28:50.089603 [info ] [MainThread]: [31m2 checks failed:[0m
[0m17:28:50.089603 [info ] [MainThread]: dbt looked for a profiles.yml file in C:\Users\marcell.oliveira\Desktop\dbt_example\profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m17:28:50.089603 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\marcell.oliveira\Desktop\dbt_example\dbt_project.yml> not found

[0m17:28:50.089603 [debug] [MainThread]: Command `dbt debug` failed at 17:28:50.089603 after 0.23 seconds
[0m17:28:50.089603 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002704D1A7950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002704D1A7CE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002704B97F3E0>]}
[0m17:28:50.089603 [debug] [MainThread]: Flushing usage events
[0m17:28:50.775714 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:32:10.275745 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BF6AE1ED80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BF6A32FBF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BF6AF0AC60>]}


============================== 17:32:10.286083 | f7b5ba8c-a6a4-4b8a-a873-f945177ea781 ==============================
[0m17:32:10.286083 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:32:10.286083 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\Desktop\\dbt_example', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt debug', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:32:10.292363 [info ] [MainThread]: dbt version: 1.9.1
[0m17:32:10.292363 [info ] [MainThread]: python version: 3.12.8
[0m17:32:10.292363 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:32:10.303624 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:32:10.303624 [info ] [MainThread]: Using profiles dir at C:\Users\marcell.oliveira\Desktop\dbt_example
[0m17:32:10.304861 [info ] [MainThread]: Using profiles.yml file at C:\Users\marcell.oliveira\Desktop\dbt_example\profiles.yml
[0m17:32:10.304861 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\marcell.oliveira\Desktop\dbt_example\dbt_project.yml
[0m17:32:10.305533 [info ] [MainThread]: Configuration:
[0m17:32:10.305533 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m17:32:10.306186 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m17:32:10.306186 [info ] [MainThread]: Required dependencies:
[0m17:32:10.307196 [debug] [MainThread]: Executing "git --help"
[0m17:32:10.378757 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m17:32:10.379909 [debug] [MainThread]: STDERR: "b''"
[0m17:32:10.379909 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m17:32:10.380926 [info ] [MainThread]: Connection test skipped since no profile was found
[0m17:32:10.381922 [info ] [MainThread]: [31m2 checks failed:[0m
[0m17:32:10.381922 [info ] [MainThread]: dbt looked for a profiles.yml file in C:\Users\marcell.oliveira\Desktop\dbt_example\profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m17:32:10.382933 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\marcell.oliveira\Desktop\dbt_example\dbt_project.yml> not found

[0m17:32:10.384233 [debug] [MainThread]: Command `dbt debug` failed at 17:32:10.384233 after 0.23 seconds
[0m17:32:10.384233 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BF682D9730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BF6AF96AE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BF6B334500>]}
[0m17:32:10.385246 [debug] [MainThread]: Flushing usage events
[0m17:32:11.019347 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:33:35.164926 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD911781D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD91179520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD911794F0>]}


============================== 17:33:35.170949 | 0de85d79-0259-4bb6-982b-fdc8d547bb0f ==============================
[0m17:33:35.170949 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:33:35.171306 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\Desktop\\dbt_example', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:33:35.184992 [info ] [MainThread]: dbt version: 1.9.1
[0m17:33:35.186041 [info ] [MainThread]: python version: 3.12.8
[0m17:33:35.186516 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:33:35.186516 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:33:35.187523 [info ] [MainThread]: Using profiles dir at C:\Users\marcell.oliveira\Desktop\dbt_example
[0m17:33:35.187523 [info ] [MainThread]: Using profiles.yml file at C:\Users\marcell.oliveira\Desktop\dbt_example\profiles.yml
[0m17:33:35.188453 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\marcell.oliveira\Desktop\dbt_example\dbt_project.yml
[0m17:33:35.188929 [info ] [MainThread]: Configuration:
[0m17:33:35.189096 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m17:33:35.189096 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m17:33:35.189096 [info ] [MainThread]: Required dependencies:
[0m17:33:35.190097 [debug] [MainThread]: Executing "git --help"
[0m17:33:35.249156 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m17:33:35.249156 [debug] [MainThread]: STDERR: "b''"
[0m17:33:35.249156 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m17:33:35.250158 [info ] [MainThread]: Connection test skipped since no profile was found
[0m17:33:35.250158 [info ] [MainThread]: [31m2 checks failed:[0m
[0m17:33:35.251159 [info ] [MainThread]: dbt looked for a profiles.yml file in C:\Users\marcell.oliveira\Desktop\dbt_example\profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m17:33:35.251159 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\marcell.oliveira\Desktop\dbt_example\dbt_project.yml> not found

[0m17:33:35.253160 [debug] [MainThread]: Command `dbt debug` failed at 17:33:35.253160 after 0.23 seconds
[0m17:33:35.254189 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD917EA900>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD90CD7AA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD91A6C560>]}
[0m17:33:35.254189 [debug] [MainThread]: Flushing usage events
[0m17:33:35.937237 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:35:58.399056 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025A40920800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025A43B4E090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025A43E033B0>]}


============================== 17:35:58.406790 | 9e8a5b3e-ec2f-44c3-a85b-aa868d087c0b ==============================
[0m17:35:58.406790 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:35:58.406790 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\Desktop\\dbt_example', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:35:58.413791 [info ] [MainThread]: dbt version: 1.9.1
[0m17:35:58.413791 [info ] [MainThread]: python version: 3.12.8
[0m17:35:58.413791 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:35:58.425582 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:35:58.425901 [info ] [MainThread]: Using profiles dir at C:\Users\marcell.oliveira\Desktop\dbt_example
[0m17:35:58.426501 [info ] [MainThread]: Using profiles.yml file at C:\Users\marcell.oliveira\Desktop\dbt_example\profiles.yml
[0m17:35:58.426501 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\marcell.oliveira\Desktop\dbt_example\dbt_project.yml
[0m17:35:58.426501 [info ] [MainThread]: Configuration:
[0m17:35:58.427905 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m17:35:58.427905 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m17:35:58.428910 [info ] [MainThread]: Required dependencies:
[0m17:35:58.428910 [debug] [MainThread]: Executing "git --help"
[0m17:35:58.495640 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m17:35:58.497153 [debug] [MainThread]: STDERR: "b''"
[0m17:35:58.497153 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m17:35:58.497153 [info ] [MainThread]: Connection test skipped since no profile was found
[0m17:35:58.497153 [info ] [MainThread]: [31m2 checks failed:[0m
[0m17:35:58.497153 [info ] [MainThread]: dbt looked for a profiles.yml file in C:\Users\marcell.oliveira\Desktop\dbt_example\profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m17:35:58.497153 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\marcell.oliveira\Desktop\dbt_example\dbt_project.yml> not found

[0m17:35:58.497153 [debug] [MainThread]: Command `dbt debug` failed at 17:35:58.497153 after 0.25 seconds
[0m17:35:58.497153 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025A445E9E20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025A43216F00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025A448A59D0>]}
[0m17:35:58.497153 [debug] [MainThread]: Flushing usage events
[0m17:35:59.180629 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:39:38.197031 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000277843EA2D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000277842D6AE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002778430D280>]}


============================== 17:39:38.203034 | 4ec5a734-40d8-4a99-922f-430dd13c9524 ==============================
[0m17:39:38.203034 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:39:38.204038 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:39:38.218494 [info ] [MainThread]: dbt version: 1.9.1
[0m17:39:38.218494 [info ] [MainThread]: python version: 3.12.8
[0m17:39:38.218494 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:39:38.219516 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:39:38.219516 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m17:39:38.220466 [debug] [MainThread]: Command `dbt debug` failed at 17:39:38.220466 after 0.10 seconds
[0m17:39:38.221467 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027783F846E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027784415010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000277844152B0>]}
[0m17:39:38.221467 [debug] [MainThread]: Flushing usage events
[0m17:39:38.908532 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:41:55.140961 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000198EE5EA0C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000198EE511D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000198EE5EA1E0>]}


============================== 17:41:55.140961 | 41041ff5-bd9a-46d9-878a-0ebe85aedd9a ==============================
[0m17:41:55.140961 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:41:55.140961 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:41:55.164144 [info ] [MainThread]: dbt version: 1.9.1
[0m17:41:55.164144 [info ] [MainThread]: python version: 3.12.8
[0m17:41:55.167433 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:41:55.167913 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:41:55.167913 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m17:41:55.169920 [debug] [MainThread]: Command `dbt debug` failed at 17:41:55.169920 after 0.10 seconds
[0m17:41:55.170922 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000198EE614F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000198EE4AAAB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000198EE5E8980>]}
[0m17:41:55.170922 [debug] [MainThread]: Flushing usage events
[0m17:41:55.826002 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:45:40.984405 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018816FE1670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018817232DE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188173EA0C0>]}


============================== 17:45:40.984405 | 94ca2206-5273-49cc-906b-3d03df1d63d2 ==============================
[0m17:45:40.984405 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:45:40.994468 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:45:41.007740 [info ] [MainThread]: dbt version: 1.9.1
[0m17:45:41.010251 [info ] [MainThread]: python version: 3.12.8
[0m17:45:41.010983 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:45:41.011496 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:45:41.012043 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m17:45:41.014227 [debug] [MainThread]: Command `dbt debug` failed at 17:45:41.014227 after 0.13 seconds
[0m17:45:41.014227 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018816EDE4B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018817418E60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018817468740>]}
[0m17:45:41.015227 [debug] [MainThread]: Flushing usage events
[0m17:45:41.709010 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:48:14.805332 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F865EA120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F86056AE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F865EA090>]}


============================== 17:48:14.821918 | 4c2b5319-2115-409d-9a59-0d51eee0e0ee ==============================
[0m17:48:14.821918 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:48:14.821918 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:48:14.838735 [info ] [MainThread]: dbt version: 1.9.1
[0m17:48:14.839928 [info ] [MainThread]: python version: 3.12.8
[0m17:48:14.839928 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:48:14.840957 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:48:14.842209 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m17:48:14.845950 [debug] [MainThread]: Command `dbt debug` failed at 17:48:14.845950 after 0.11 seconds
[0m17:48:14.845950 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F86512150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F86618FB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F86619250>]}
[0m17:48:14.846950 [debug] [MainThread]: Flushing usage events
[0m17:48:15.510861 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:49:46.813213 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B9F7383B30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B9F794BFB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B9F780A390>]}


============================== 17:49:46.813903 | 721eb885-9ba9-4442-badb-d0a43a1150dd ==============================
[0m17:49:46.813903 [info ] [MainThread]: Running with dbt=1.9.1
[0m17:49:46.813903 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\Desktop\\dbt_example', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m17:49:46.834966 [info ] [MainThread]: dbt version: 1.9.1
[0m17:49:46.834966 [info ] [MainThread]: python version: 3.12.8
[0m17:49:46.834966 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m17:49:46.834966 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m17:49:46.834966 [info ] [MainThread]: Using profiles dir at C:\Users\marcell.oliveira\Desktop\dbt_example
[0m17:49:46.834966 [info ] [MainThread]: Using profiles.yml file at C:\Users\marcell.oliveira\Desktop\dbt_example\profiles.yml
[0m17:49:46.834966 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\marcell.oliveira\Desktop\dbt_example\dbt_project.yml
[0m17:49:46.834966 [info ] [MainThread]: Configuration:
[0m17:49:46.834966 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m17:49:46.834966 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m17:49:46.834966 [info ] [MainThread]: Required dependencies:
[0m17:49:46.834966 [debug] [MainThread]: Executing "git --help"
[0m17:49:46.895489 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m17:49:46.903211 [debug] [MainThread]: STDERR: "b''"
[0m17:49:46.903211 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m17:49:46.903211 [info ] [MainThread]: Connection test skipped since no profile was found
[0m17:49:46.903211 [info ] [MainThread]: [31m2 checks failed:[0m
[0m17:49:46.903211 [info ] [MainThread]: dbt looked for a profiles.yml file in C:\Users\marcell.oliveira\Desktop\dbt_example\profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m17:49:46.903211 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\marcell.oliveira\Desktop\dbt_example\dbt_project.yml> not found

[0m17:49:46.903211 [debug] [MainThread]: Command `dbt debug` failed at 17:49:46.903211 after 0.25 seconds
[0m17:49:46.903211 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B9F8A0CB30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B9F544D250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B9F7CDAE70>]}
[0m17:49:46.903211 [debug] [MainThread]: Flushing usage events
[0m17:49:47.515396 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:01:51.488741 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D04BAEA0F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D04BAE9CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D04BAEA150>]}


============================== 18:01:51.488741 | df081ca8-1075-4cc4-9fb6-c097c3a44dcd ==============================
[0m18:01:51.488741 [info ] [MainThread]: Running with dbt=1.9.1
[0m18:01:51.488741 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m18:01:51.500509 [info ] [MainThread]: dbt version: 1.9.1
[0m18:01:51.500509 [info ] [MainThread]: python version: 3.12.8
[0m18:01:51.500509 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m18:01:51.514160 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m18:01:51.515106 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m18:01:51.517046 [debug] [MainThread]: Command `dbt debug` failed at 18:01:51.517046 after 0.13 seconds
[0m18:01:51.517046 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D04BB18E90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D04BB68740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D04BAEA210>]}
[0m18:01:51.518359 [debug] [MainThread]: Flushing usage events
[0m18:01:52.155444 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:14:42.127412 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C3B34E9FA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C3B34EA0F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C3B34EA1B0>]}


============================== 14:14:42.172600 | 3f3f6a84-d1ce-4194-b9cb-22073935e892 ==============================
[0m14:14:42.172600 [info ] [MainThread]: Running with dbt=1.9.1
[0m14:14:42.174484 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:14:42.280924 [info ] [MainThread]: dbt version: 1.9.1
[0m14:14:42.280924 [info ] [MainThread]: python version: 3.12.8
[0m14:14:42.281789 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m14:14:42.281789 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:14:42.282766 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m14:14:42.283790 [debug] [MainThread]: Command `dbt debug` failed at 14:14:42.283790 after 0.28 seconds
[0m14:14:42.283790 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C3B3518F80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C3B3564950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C3B2F7AAB0>]}
[0m14:14:42.284792 [debug] [MainThread]: Flushing usage events
[0m14:14:42.900749 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:17:30.554235 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D6BC45CEC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D6BC812DE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D6BC8E9CD0>]}


============================== 14:17:30.569864 | 8fd876ea-4980-4e28-8d9e-3b328f810c18 ==============================
[0m14:17:30.569864 [info ] [MainThread]: Running with dbt=1.9.1
[0m14:17:30.569864 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m14:17:30.586734 [info ] [MainThread]: dbt version: 1.9.1
[0m14:17:30.586734 [info ] [MainThread]: python version: 3.12.8
[0m14:17:30.590462 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m14:17:30.590536 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:17:30.591593 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m14:17:30.592745 [debug] [MainThread]: Command `dbt debug` failed at 14:17:30.592745 after 0.11 seconds
[0m14:17:30.592745 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D6BC918E00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D6BC968740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D6BC8E9F70>]}
[0m14:17:30.592745 [debug] [MainThread]: Flushing usage events
[0m14:17:31.239508 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:18:41.492157 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A1417864E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A141BEA210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A141BEA3C0>]}


============================== 14:18:41.505196 | 632b2abd-ed76-4ab8-b3a6-828d55157388 ==============================
[0m14:18:41.505196 [info ] [MainThread]: Running with dbt=1.9.1
[0m14:18:41.505196 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m14:18:41.526013 [info ] [MainThread]: dbt version: 1.9.1
[0m14:18:41.526013 [info ] [MainThread]: python version: 3.12.8
[0m14:18:41.526013 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m14:18:41.526013 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:18:41.530381 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m14:18:41.533483 [debug] [MainThread]: Command `dbt debug` failed at 14:18:41.533483 after 0.14 seconds
[0m14:18:41.533483 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A14160B9B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A141C19010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A141BEA390>]}
[0m14:18:41.533483 [debug] [MainThread]: Flushing usage events
[0m14:18:42.223002 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:19:20.312007 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ED8CEA180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ED88E3860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ED8CEA240>]}


============================== 14:19:20.312007 | 21f2431b-e8be-495e-95ba-b70074806846 ==============================
[0m14:19:20.312007 [info ] [MainThread]: Running with dbt=1.9.1
[0m14:19:20.312007 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:19:20.335855 [info ] [MainThread]: dbt version: 1.9.1
[0m14:19:20.335855 [info ] [MainThread]: python version: 3.12.8
[0m14:19:20.335855 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m14:19:20.337769 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:19:20.337769 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m14:19:20.340177 [debug] [MainThread]: Command `dbt debug` failed at 14:19:20.340177 after 0.13 seconds
[0m14:19:20.340177 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ED8C11790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ED8D150D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ED86B2EA0>]}
[0m14:19:20.340177 [debug] [MainThread]: Flushing usage events
[0m14:19:20.906634 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:19:41.042553 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000272ED8EA1E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000272ED53ADE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000272ED811D90>]}


============================== 14:19:41.042553 | d02d46de-20fc-4180-8c77-b19aff1d8865 ==============================
[0m14:19:41.042553 [info ] [MainThread]: Running with dbt=1.9.1
[0m14:19:41.050628 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt debug', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:19:41.063773 [info ] [MainThread]: dbt version: 1.9.1
[0m14:19:41.064881 [info ] [MainThread]: python version: 3.12.8
[0m14:19:41.065388 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m14:19:41.065388 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:19:41.066393 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m14:19:41.067392 [debug] [MainThread]: Command `dbt debug` failed at 14:19:41.067392 after 0.12 seconds
[0m14:19:41.067392 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000272ED4A7E90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000272ED919280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000272ED53AEA0>]}
[0m14:19:41.068393 [debug] [MainThread]: Flushing usage events
[0m14:19:41.695298 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:26:49.851642 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EFF34EA2A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EFF1DAB860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EFF340D280>]}


============================== 14:26:49.867236 | 17e8d022-af3f-494d-bb2c-cc8ff1a11978 ==============================
[0m14:26:49.867236 [info ] [MainThread]: Running with dbt=1.9.1
[0m14:26:49.867236 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:26:49.867236 [info ] [MainThread]: dbt version: 1.9.1
[0m14:26:49.867236 [info ] [MainThread]: python version: 3.12.8
[0m14:26:49.867236 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m14:26:49.882214 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:26:49.882875 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m14:26:49.886356 [debug] [MainThread]: Command `dbt debug` failed at 14:26:49.886356 after 0.11 seconds
[0m14:26:49.886883 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EFF3515040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EFF340E990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EFF316E360>]}
[0m14:26:49.886883 [debug] [MainThread]: Flushing usage events
[0m14:26:50.527678 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:30:10.584572 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001637E6EA300>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001637E156AE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001637E6EA2A0>]}


============================== 14:30:10.600191 | c48c6bc7-c11e-4380-81f6-c1f314cf5a1b ==============================
[0m14:30:10.600191 [info ] [MainThread]: Running with dbt=1.9.1
[0m14:30:10.600191 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt debug --project-dir C:\\Users\\marcell.oliveira\\Desktop\\dbt_example', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:30:10.615887 [info ] [MainThread]: dbt version: 1.9.1
[0m14:30:10.615887 [info ] [MainThread]: python version: 3.12.8
[0m14:30:10.615887 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m14:30:10.615887 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:30:10.615887 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m14:30:10.615887 [debug] [MainThread]: Command `dbt debug` failed at 14:30:10.615887 after 0.15 seconds
[0m14:30:10.615887 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001637E2E3D70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001637E719130>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001637E6EA630>]}
[0m14:30:10.615887 [debug] [MainThread]: Flushing usage events
[0m14:30:11.324184 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:31:16.518350 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F188EE330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F172AB8C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F1837B3B0>]}


============================== 14:31:16.534723 | 91d4c484-ae88-4180-a99c-0532af48faee ==============================
[0m14:31:16.534723 [info ] [MainThread]: Running with dbt=1.9.1
[0m14:31:16.534723 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug --project-dir C:\\Users\\marcell.oliveira\\Desktop\\dbt_example\\dbt_example\\dbt_project.yml', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:31:16.551283 [info ] [MainThread]: dbt version: 1.9.1
[0m14:31:16.552328 [info ] [MainThread]: python version: 3.12.8
[0m14:31:16.553338 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m14:31:16.554291 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:31:16.554291 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m14:31:16.556194 [debug] [MainThread]: Command `dbt debug` failed at 14:31:16.556194 after 0.13 seconds
[0m14:31:16.556194 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F18942330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F18918EF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F1891AEA0>]}
[0m14:31:16.556194 [debug] [MainThread]: Flushing usage events
[0m14:31:17.217186 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:35:45.881746 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018BA3CEA270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018BA3CEA300>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018BA3CEA3C0>]}


============================== 14:35:45.881746 | 978b910d-eb1a-4db4-89d1-1544a8606ecb ==============================
[0m14:35:45.881746 [info ] [MainThread]: Running with dbt=1.9.1
[0m14:35:45.881746 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:35:45.897515 [info ] [MainThread]: dbt version: 1.9.1
[0m14:35:45.897515 [info ] [MainThread]: python version: 3.12.8
[0m14:35:45.897515 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m14:35:45.908145 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:35:45.908824 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m14:35:45.911268 [debug] [MainThread]: Command `dbt debug` failed at 14:35:45.910004 after 0.11 seconds
[0m14:35:45.911268 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018BA39D4560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018BA3D3D970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018BA3CEA330>]}
[0m14:35:45.911818 [debug] [MainThread]: Flushing usage events
[0m14:35:46.561470 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:36:07.445101 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC87FEA240>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC87E32DE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC87FEA2D0>]}


============================== 14:36:07.445101 | cde13fe6-54c9-445b-b1c1-6cd6c69f1339 ==============================
[0m14:36:07.445101 [info ] [MainThread]: Running with dbt=1.9.1
[0m14:36:07.445101 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt debug --profiles-dir C:\\Users\\marcell.oliveira\\.dbt', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:36:07.461665 [info ] [MainThread]: dbt version: 1.9.1
[0m14:36:07.461665 [info ] [MainThread]: python version: 3.12.8
[0m14:36:07.461665 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m14:36:07.461665 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:36:07.474778 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m14:36:07.476891 [debug] [MainThread]: Command `dbt debug` failed at 14:36:07.476891 after 0.12 seconds
[0m14:36:07.476891 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC87ED4530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC87FEA2A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC87FEA300>]}
[0m14:36:07.476891 [debug] [MainThread]: Flushing usage events
[0m14:36:08.138385 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:40:51.276653 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190419D1610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190419D16D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190419D1430>]}


============================== 14:40:51.283659 | 79f3239c-7709-4ecd-9059-696ba226c133 ==============================
[0m14:40:51.283659 [info ] [MainThread]: Running with dbt=1.8.9
[0m14:40:51.284585 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt compile', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:40:51.284585 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\marcell.oliveira\Desktop\dbt_example\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:40:51.286607 [debug] [MainThread]: Command `dbt compile` failed at 14:40:51.286607 after 0.10 seconds
[0m14:40:51.287505 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001903C56B950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019041697EC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190419AFB60>]}
[0m14:40:51.287505 [debug] [MainThread]: Flushing usage events
[0m14:41:06.264471 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209C21D1910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209C21D19D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209C21D1880>]}


============================== 14:41:06.271185 | fa8b3515-10ba-4eaf-9829-a5c2b92c8cb7 ==============================
[0m14:41:06.271185 [info ] [MainThread]: Running with dbt=1.8.9
[0m14:41:06.271331 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt build', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:41:06.272389 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\marcell.oliveira\Desktop\dbt_example\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:41:06.273728 [debug] [MainThread]: Command `dbt build` failed at 14:41:06.273728 after 0.10 seconds
[0m14:41:06.273728 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209C20B8620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209C14DEE70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209C21D12B0>]}
[0m14:41:06.273728 [debug] [MainThread]: Flushing usage events
[0m14:41:27.466992 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022EC1161670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022EBFF74560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022EC102B770>]}


============================== 14:41:27.482947 | 3b49e835-827e-47e9-bfed-3a49620b9445 ==============================
[0m14:41:27.482947 [info ] [MainThread]: Running with dbt=1.8.9
[0m14:41:27.482947 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:41:27.482947 [info ] [MainThread]: dbt version: 1.8.9
[0m14:41:27.482947 [info ] [MainThread]: python version: 3.12.8
[0m14:41:27.482947 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m14:41:27.498859 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:41:27.499290 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m14:41:27.503446 [debug] [MainThread]: Command `dbt debug` failed at 14:41:27.503446 after 0.10 seconds
[0m14:41:27.503446 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022EBBE1BCB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022EC1196E40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022EC14D2960>]}
[0m14:41:27.505034 [debug] [MainThread]: Flushing usage events
[0m14:43:38.063809 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000134E18AFDA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000134E1603EC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000134E18AFEC0>]}


============================== 14:43:38.065315 | dae7583d-21f1-4fed-a63a-a0f3de7da972 ==============================
[0m14:43:38.065315 [info ] [MainThread]: Running with dbt=1.8.9
[0m14:43:38.065315 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:43:38.085802 [info ] [MainThread]: dbt version: 1.8.9
[0m14:43:38.085802 [info ] [MainThread]: python version: 3.12.8
[0m14:43:38.086802 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m14:43:38.086802 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:43:38.087801 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m14:43:38.089903 [debug] [MainThread]: Command `dbt debug` failed at 14:43:38.089903 after 0.11 seconds
[0m14:43:38.089903 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000134E161E000>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000134E1942C00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000134DC0FBCB0>]}
[0m14:43:38.089903 [debug] [MainThread]: Flushing usage events
[0m14:45:18.700214 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000145C95AFEF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000145C95AFF80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000145C95AFAD0>]}


============================== 14:45:18.710623 | 83db1d84-7b60-459c-a2b7-73ce8512601f ==============================
[0m14:45:18.710623 [info ] [MainThread]: Running with dbt=1.8.9
[0m14:45:18.711570 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:45:18.724681 [info ] [MainThread]: dbt version: 1.8.9
[0m14:45:18.726070 [info ] [MainThread]: python version: 3.12.8
[0m14:45:18.726563 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m14:45:18.726563 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:45:18.727569 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m14:45:18.731276 [debug] [MainThread]: Command `dbt debug` failed at 14:45:18.731050 after 0.15 seconds
[0m14:45:18.731276 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000145C95AFAD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000145C9487EC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000145C9296E70>]}
[0m14:45:18.731276 [debug] [MainThread]: Flushing usage events
[0m14:45:50.860149 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F0D1AFD10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F0D1AFCE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F0D1AFDA0>]}


============================== 14:45:50.860149 | 9c406589-1bb5-4884-a3e9-58db379ba4e9 ==============================
[0m14:45:50.860149 [info ] [MainThread]: Running with dbt=1.8.9
[0m14:45:50.860149 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:45:50.881799 [info ] [MainThread]: dbt version: 1.8.9
[0m14:45:50.881799 [info ] [MainThread]: python version: 3.12.8
[0m14:45:50.881799 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m14:45:50.886775 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:45:50.887785 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m14:45:50.889509 [debug] [MainThread]: Command `dbt debug` failed at 14:45:50.889509 after 0.11 seconds
[0m14:45:50.889509 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F0D08BAD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F0CF5BD70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F0D1D2930>]}
[0m14:45:50.889509 [debug] [MainThread]: Flushing usage events
[0m14:46:12.126813 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234A3CAFF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234A3CAFAD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234A3CAFFB0>]}


============================== 14:46:12.130556 | 0de55791-e438-4db9-be90-bba85a225b68 ==============================
[0m14:46:12.130556 [info ] [MainThread]: Running with dbt=1.8.9
[0m14:46:12.130556 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:46:12.145579 [info ] [MainThread]: dbt version: 1.8.9
[0m14:46:12.147028 [info ] [MainThread]: python version: 3.12.8
[0m14:46:12.147499 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m14:46:12.147883 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:46:12.148915 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m14:46:12.151984 [debug] [MainThread]: Command `dbt debug` failed at 14:46:12.151984 after 0.11 seconds
[0m14:46:12.151984 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234A397C7D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234A3CAFFB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234A3D42C00>]}
[0m14:46:12.151984 [debug] [MainThread]: Flushing usage events
[0m14:50:31.538049 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001705BA59670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001705BA01B20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001705BCAFEF0>]}


============================== 14:50:31.545527 | c4626ece-fc75-4370-81a9-93b51cefd73a ==============================
[0m14:50:31.545527 [info ] [MainThread]: Running with dbt=1.8.9
[0m14:50:31.546541 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:50:31.560529 [info ] [MainThread]: dbt version: 1.8.9
[0m14:50:31.561529 [info ] [MainThread]: python version: 3.12.8
[0m14:50:31.562625 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m14:50:31.563633 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:50:31.564634 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m14:50:31.566189 [debug] [MainThread]: Command `dbt debug` failed at 14:50:31.566189 after 0.15 seconds
[0m14:50:31.567293 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001705BA59670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001705BCD2A80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001705AA602C0>]}
[0m14:50:31.567293 [debug] [MainThread]: Flushing usage events
[0m15:10:01.798062 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B456DAFF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B45678B3B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B456DAFAD0>]}


============================== 15:10:01.798062 | 982913fe-3fec-4e31-be8b-ebad1b3f2ac2 ==============================
[0m15:10:01.798062 [info ] [MainThread]: Running with dbt=1.8.9
[0m15:10:01.798062 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:10:01.810169 [info ] [MainThread]: dbt version: 1.8.9
[0m15:10:01.810169 [info ] [MainThread]: python version: 3.12.8
[0m15:10:01.810169 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m15:10:01.819565 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m15:10:01.820315 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m15:10:01.822439 [debug] [MainThread]: Command `dbt debug` failed at 15:10:01.822439 after 0.11 seconds
[0m15:10:01.822941 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B45678BFE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B456E48260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B456A05A00>]}
[0m15:10:01.822941 [debug] [MainThread]: Flushing usage events
[0m15:11:19.590241 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174F40AFC80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174F40AFD10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174F40AFD70>]}


============================== 15:11:19.590241 | f7900eb1-8495-46a1-aadd-cec40b3732ae ==============================
[0m15:11:19.590241 [info ] [MainThread]: Running with dbt=1.8.9
[0m15:11:19.590241 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:11:19.611839 [info ] [MainThread]: dbt version: 1.8.9
[0m15:11:19.611839 [info ] [MainThread]: python version: 3.12.8
[0m15:11:19.616142 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m15:11:19.616549 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m15:11:19.616549 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m15:11:19.618558 [debug] [MainThread]: Command `dbt debug` failed at 15:11:19.618558 after 0.12 seconds
[0m15:11:19.619555 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174F3D97FB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174F2FC54C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174F40AFE00>]}
[0m15:11:19.619555 [debug] [MainThread]: Flushing usage events
[0m15:12:25.210005 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED54BAFDD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED54BAFF80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED54BAFFE0>]}


============================== 15:12:25.214620 | 4d2098bc-73f9-4e61-b6c0-d4771ccdb187 ==============================
[0m15:12:25.214620 [info ] [MainThread]: Running with dbt=1.8.9
[0m15:12:25.214620 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:12:25.232148 [info ] [MainThread]: dbt version: 1.8.9
[0m15:12:25.232148 [info ] [MainThread]: python version: 3.12.8
[0m15:12:25.238699 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m15:12:25.238699 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m15:12:25.238699 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m15:12:25.245116 [debug] [MainThread]: Command `dbt debug` failed at 15:12:25.245116 after 0.15 seconds
[0m15:12:25.245116 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED54E24140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED4F748230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED54AB8590>]}
[0m15:12:25.246226 [debug] [MainThread]: Flushing usage events
[0m15:13:25.551129 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DAF3CAFF20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DAF3CAFEF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DAF3CAFFE0>]}


============================== 15:13:25.557766 | 747bd3fc-0f46-4c5d-ac46-1df8204cf8b4 ==============================
[0m15:13:25.557766 [info ] [MainThread]: Running with dbt=1.8.9
[0m15:13:25.557766 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:13:25.557766 [info ] [MainThread]: dbt version: 1.8.9
[0m15:13:25.557766 [info ] [MainThread]: python version: 3.12.8
[0m15:13:25.557766 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m15:13:25.572543 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m15:13:25.573500 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m15:13:25.576667 [debug] [MainThread]: Command `dbt debug` failed at 15:13:25.576667 after 0.11 seconds
[0m15:13:25.576667 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DAEE53B020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DAF3997230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DAF35F14C0>]}
[0m15:13:25.576667 [debug] [MainThread]: Flushing usage events
[0m15:15:06.696479 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B4B82AFF20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B4B82AFEF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B4B82AFAD0>]}


============================== 15:15:06.702041 | c498fabe-cccb-491c-bbfe-d927be290345 ==============================
[0m15:15:06.702041 [info ] [MainThread]: Running with dbt=1.8.9
[0m15:15:06.702041 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:15:06.702041 [info ] [MainThread]: dbt version: 1.8.9
[0m15:15:06.702041 [info ] [MainThread]: python version: 3.12.8
[0m15:15:06.702041 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m15:15:06.702041 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m15:15:06.702041 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m15:15:06.718701 [debug] [MainThread]: Command `dbt debug` failed at 15:15:06.717804 after 0.12 seconds
[0m15:15:06.718701 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B4B81878C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B4B82AFEF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B4B83241D0>]}
[0m15:15:06.718701 [debug] [MainThread]: Flushing usage events
[0m15:21:34.419268 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021BFC1D11F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021BFBF578C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021BFC1D00B0>]}


============================== 15:21:34.425951 | 06791906-d9de-4bcc-bdd9-9081290b241d ==============================
[0m15:21:34.425951 [info ] [MainThread]: Running with dbt=1.8.9
[0m15:21:34.426833 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:21:34.438917 [info ] [MainThread]: dbt version: 1.8.9
[0m15:21:34.438917 [info ] [MainThread]: python version: 3.12.8
[0m15:21:34.438917 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m15:21:34.439857 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m15:21:34.439857 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m15:21:34.440864 [debug] [MainThread]: Command `dbt debug` failed at 15:21:34.440864 after 0.11 seconds
[0m15:21:34.441927 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021BF6B2B020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021BFC0B8590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021BFBF017C0>]}
[0m15:21:34.441927 [debug] [MainThread]: Flushing usage events
[0m15:23:07.008001 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B5FF0AFF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B5FEDCF8C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B5FF0AFEF0>]}


============================== 15:23:07.008819 | 72d0324c-e818-4b03-9223-4ea0776bf6f3 ==============================
[0m15:23:07.008819 [info ] [MainThread]: Running with dbt=1.8.9
[0m15:23:07.008819 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:23:07.030951 [info ] [MainThread]: dbt version: 1.8.9
[0m15:23:07.032027 [info ] [MainThread]: python version: 3.12.8
[0m15:23:07.032027 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m15:23:07.032027 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m15:23:07.033557 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m15:23:07.035511 [debug] [MainThread]: Command `dbt debug` failed at 15:23:07.035511 after 0.12 seconds
[0m15:23:07.035511 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B5FEDCF8C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B5FEFB88C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B5FF143320>]}
[0m15:23:07.035511 [debug] [MainThread]: Flushing usage events
[0m15:27:17.780142 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190125AFD10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019012303EC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190125AFC80>]}


============================== 15:27:17.795758 | d99f8609-918f-485f-b07d-8b40457da4eb ==============================
[0m15:27:17.795758 [info ] [MainThread]: Running with dbt=1.8.9
[0m15:27:17.795758 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt debug', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:27:17.795758 [info ] [MainThread]: dbt version: 1.8.9
[0m15:27:17.795758 [info ] [MainThread]: python version: 3.12.8
[0m15:27:17.795758 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m15:27:17.795758 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m15:27:17.795758 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m15:27:17.811414 [debug] [MainThread]: Command `dbt debug` failed at 15:27:17.811414 after 0.12 seconds
[0m15:27:17.811414 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001900CEDB020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019012445640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190118F6E70>]}
[0m15:27:17.811414 [debug] [MainThread]: Flushing usage events
[0m15:29:56.396713 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A0EED2F3E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A0F1764560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A0F22B7140>]}


============================== 15:29:56.400729 | a1ab654c-1908-4b50-bf18-92fc2856b999 ==============================
[0m15:29:56.400729 [info ] [MainThread]: Running with dbt=1.8.9
[0m15:29:56.400729 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m15:29:56.400729 [info ] [MainThread]: dbt version: 1.8.9
[0m15:29:56.416365 [info ] [MainThread]: python version: 3.12.8
[0m15:29:56.416365 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m15:29:56.416365 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m15:29:56.416365 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m15:29:56.416365 [debug] [MainThread]: Command `dbt debug` failed at 15:29:56.416365 after 0.11 seconds
[0m15:29:56.416365 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A0F2100AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A0F2222FF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A0F2494290>]}
[0m15:29:56.416365 [debug] [MainThread]: Flushing usage events
[0m15:36:43.283659 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D9CF6AFE30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D9CF6AFE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D9CF6AFD70>]}


============================== 15:36:43.291661 | 57d72d45-c339-4fdd-a642-6960c8981e43 ==============================
[0m15:36:43.291661 [info ] [MainThread]: Running with dbt=1.8.9
[0m15:36:43.293662 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcell.oliveira\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m15:36:43.306660 [info ] [MainThread]: dbt version: 1.8.9
[0m15:36:43.307670 [info ] [MainThread]: python version: 3.12.8
[0m15:36:43.308615 [info ] [MainThread]: python path: C:\Users\marcell.oliveira\Desktop\dbt_example\.venv\Scripts\python.exe
[0m15:36:43.309624 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m15:36:43.310702 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 3
  ------------------------------
  1  | dbt_example:
  2  |  target: dev
  3  |     outputs:
  4  |       dev:
  5  |         type: bigquery
  6  |         method: service-account
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 3, column 12
[0m15:36:43.310702 [debug] [MainThread]: Command `dbt debug` failed at 15:36:43.310702 after 0.14 seconds
[0m15:36:43.315073 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D9CFA28260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D9CF6D2A80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D9CF4FD5E0>]}
[0m15:36:43.315073 [debug] [MainThread]: Flushing usage events
